name: 'ecom_dbt_transforms'
version: '1.0.0'
config-version: 2

profile: 'ecom_dbt_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecom_dbt_transforms:
    silver:
      +materialized: table
    gold:
      +materialized: table
